"use client"
import { useState } from "react"
import { ChevronDown, ChevronUp } from "lucide-react"
import { Section } from "./section"
import { SectionHeader } from "./section-header"
import { cn } from "@/lib/utils"
import { motion, AnimatePresence } from "framer-motion"

interface FAQItemProps {
  question: string
  answer: string
  isOpen: boolean
  onClick: () => void
  isAIRelated?: boolean
}

function FAQItem({ question, answer, isOpen, onClick, isAIRelated = false }: FAQItemProps) {
  return (
    <motion.div
      className={cn(
        "border border-gray-200 rounded-xl overflow-hidden mb-4 shadow-sm transition-all duration-200",
        isOpen ? "shadow-md" : "",
        isAIRelated ? "border-primary/30" : "",
      )}
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      whileHover={{ scale: 1.01 }}
    >
      <button
        className={cn(
          "w-full flex items-center justify-between p-4 text-left transition-colors duration-200",
          isOpen ? (isAIRelated ? "bg-primary/5" : "bg-primary/5") : "bg-white hover:bg-gray-50",
        )}
        onClick={onClick}
      >
        <span className="font-medium text-secondary flex items-center">
          {isAIRelated && <span className="inline-block w-2 h-2 bg-primary rounded-full mr-2"></span>}
          {question}
          {isAIRelated && <span className="ml-2 text-xs bg-primary/10 text-primary px-2 py-0.5 rounded-full">AI</span>}
        </span>
        <motion.div initial={false} animate={{ rotate: isOpen ? 180 : 0 }} transition={{ duration: 0.2 }}>
          {isOpen ? <ChevronUp className="h-5 w-5 text-primary" /> : <ChevronDown className="h-5 w-5 text-accent" />}
        </motion.div>
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <div className="p-4 bg-white border-t">
              <p className="text-gray-700">{answer}</p>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  )
}

export function FAQ() {
  const [openIndex, setOpenIndex] = useState(0)

  const faqItems = [
    {
      question: "How does Virallyzer's AI content generation work?",
      answer:
        "Virallyzer uses advanced artificial intelligence to analyze your style, audience, and goals to generate highly engaging content. Our AI models are trained on millions of high-performing social media posts and marketing content to ensure quality and effectiveness.",
      isAIRelated: true,
    },
    {
      question: "How long does it take to see results?",
      answer:
        "Most creators start seeing results within the first 7 days of use. After 30 days, our users report an average increase of 37% in engagement and conversions.",
    },
    {
      question: "Does Virallyzer have access to my photos and videos?",
      answer:
        "No. Virallyzer does not access, process, or store your photos and videos. Our AI works only with text, and you maintain 100% control over your visual content.",
    },
    {
      question: "Can I cancel at any time?",
      answer:
        "Yes, you can cancel your subscription at any time with no additional fees or loyalty periods. You maintain access until the end of the paid period.",
    },
    {
      question: "Is the generated content unique to me?",
      answer:
        "Yes, all content generated by Virallyzer is personalized according to your style, tone of voice, and specific goals. It's not generic or reused content.",
      isAIRelated: true,
    },
    {
      question: "Do I need technical knowledge to use it?",
      answer:
        "No, Virallyzer was designed to be extremely easy to use. Our intuitive interface allows you to start generating quality content in minutes, with no technical knowledge required.",
    },
    {
      question: "How does Virallyzer compare to hiring a content writer?",
      answer:
        "Virallyzer offers 24/7 availability, consistent quality, and costs a fraction of hiring a professional writer. While human writers bring unique creativity, our AI can generate content in seconds, learn your style over time, and scale with your needs without additional cost.",
      isAIRelated: true,
    },
  ]

  return (
    <Section background="white">
      <SectionHeader title="Frequently Asked Questions" subtitle="Get answers about Virallyzer" withLine />

      <motion.div
        className="max-w-3xl mx-auto"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ staggerChildren: 0.1 }}
      >
        {faqItems.map((item, index) => (
          <FAQItem
            key={index}
            question={item.question}
            answer={item.answer}
            isOpen={index === openIndex}
            onClick={() => setOpenIndex(index === openIndex ? -1 : index)}
            isAIRelated={item.isAIRelated}
          />
        ))}
      </motion.div>
    </Section>
  )
}
